### PR TITLE
Problem: On update SWR was not refetching new data

### PR DESCRIPTION
**Pull request by mgarf**
Solution: Migrate the subscription from onMount to beforeUpdate.

Theory: onMount is too early in the lifecycle for reactivity

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
Is beforeUpdate also called before first render?

**Comment by mgarf** [comment]
Based on my testing and this: https://svelte.dev/tutorial/update

I wouldn't merge this yet though. I've barely tested it outside of ensuring it fixed my use case. I wanted it created so others can test out the changes as well

**Comment by ConsoleTVs** [comment]
Awesome, will wait a bit. Happy you could step in on this!

**Comment by ConsoleTVs** [comment]
@mgarf Any news?

**Comment by mgarf** [comment]
been buried, should have time this week

**Comment by marekdedic** [comment]
Hi,
I can confirm this PR fixes #24 for me.

**Comment by ConsoleTVs** [comment]
@marekdedic Can yo u fix the conflicts on src/sswr.ts? If so, this is ready for merge

**Comment by marekdedic** [comment]
Umm, you mean [3d5a618](https://github.com/ConsoleTVs/sswr/pull/33/commits/3d5a6182139f2065fd185fffba655877826896c0)? That should cause no problems... Or do you mean something else?

**Comment by ConsoleTVs** [comment]
I'll make a release in a few min/h

**Pull request merged**
