### PR TITLE
add `stop`, `isLoading` and `isValid`

### PR DESCRIPTION
**Pull request by frederikhors**
~Fixes 4.~

~@kevmodrome what do you think?~

I reverted the rename as requested by @ConsoleTVs.

This PR now only adds `stop`, `isLoading` and `isValid`.

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
It needs some more thinking, if somebody creates a custom instance, I want it to have exactly the same method names available to him.

I also just noticed I did not expose all methods by default, check: https://github.com/ConsoleTVs/vswr/blob/master/src/index.ts

If you could address this, I would be really happy!!

**Comment by frederikhors** [comment]
I added `stop`, `isLoading` and `isValid`.

I cannot understand `stop()` from `vswr`. Can you better explain what it does?

**Comment by ConsoleTVs** [comment]
It just unsubscribes from the cache, avoids updating the value if a value in the cache is changed

**Comment by frederikhors** [comment]
Sorry I meant `loading()`. `stop()` is done.

**Comment by ConsoleTVs** [comment]
isLoading will be true whenever a request has started to fetch the data but it's not yet completed (the promise is not yet resolved). Basically there's no data nor error yet. This is where you would show some placeholder data like those loading animation: https://tailwindcss.com/docs/animation#pulse

**Comment by ConsoleTVs** [comment]
I have updated the branch, resolve the conflicts and we're good to go!!

**Comment by frederikhors** [comment]
> isLoading will be true whenever a request has started to fetch the data but it's not yet completed (the promise is not yet resolved). Basically there's no data nor error yet. This is where you would show some placeholder data like those loading animation: https://tailwindcss.com/docs/animation#pulse

`isLoading` is clear to me.

I am asking for info about `loading` I see in `vswr`.

If you think we should add it here too.

**Comment by frederikhors** [comment]
> I'll like to keep the useSWR base name

So I can revert the first commit? I'll leave it as it was, right?

**Comment by frederikhors** [comment]
I reverted the rename.

This PR now only adds `stop`, `isLoading` and `isValid`.

**Comment by benbender** [comment]
Just as a note: most of those state-booleans are mutually exclusive and should be internally combined at some point to reflect that. F.e. if a query is loading, it can't be valid or invalid. If that's not reflected, there will be edge-cases at some point. I would suggest to basically use a finite state-machine internally to determine exactly which state is actually true and which state-transitions can happen at any given point in time according to that state.

**Comment by frederikhors** [comment]
If a query `isLoading` it can be valid or not. I think in this case `isStale` is a better name.

**Comment by benbender** [comment]
The request can't be valid as the result of the request isn't determined yet while it's loading... In state-machine terms it is in state "loading" and can transition to (f.e.) "success", "canceled" or "error". It can only have one of those states at a given point in time. 

Things like "fresh" or "stale" could be states of an associated cache-object (which might be related in a common stategraph) but aren't states of the request itself.

And as always: naming is hard ;)

**Pull request closed without merging**
